Bug fixes; Also, added functionality to first check for updates before attempting yum update.

diff --git a/templates/default/auto-patch.sh.erb b/templates/default/auto-patch.sh.erb
--- a/templates/default/auto-patch.sh.erb
+++ b/templates/default/auto-patch.sh.erb
@@ -18,43 +18,50 @@ function writeHostAndLogFile {
 #  Param 1: [string] The subject of the message to send
 #  Param 2: [string] The plain-text body of the message to send
 function sendEmail {
-  to=derek.bromenshenkel@nativex.com
-  #to=<%= node["autopatch-nativex"]["email_to_addresses"].split(',').map {|x| x.gsub(/"/, "").strip}.join(',') %>
+  to=<%= node["autopatch-nativex"]["email_to_addresses"].split(',').map {|x| x.gsub(/"/, "").strip}.join(',') %>
   from=<%= node["autopatch-nativex"]["email_from_address"] %>
   subject=$1
-  body=$2
+  body="$2"
 
-  echo $body | mailx -s "$subject" -r "$from" -a "<%= node["autopatch-nativex"]["working_dir"] %>/autopatch.log" -S smtp="<%= node["autopatch-nativex"]["email_smtp_server"] %>" "$to"
+  echo "$body" | mailx -s "$subject" -r "$from" -a "<%= node["autopatch-nativex"]["working_dir"] %>/autopatch.log" -S smtp="<%= node["autopatch-nativex"]["email_smtp_server"] %>" "$to"
 }
 
 # Based on configuration and the status of the process, conditionally sends an email
-#  Param 1: [string] true or false, indicating whether manual reboot is required
-#  Param 2: [integer], return code of previous process 
+#  Param 1: [string] true or false, indicating whether yum update was attempted
+#  Param 2: [string] true or false, indicating whether manual reboot is required
+#  Param 3: [integer], return code of previous process
 function sendMailIfNecessary {
+  updateAttempted=$1
+  manualReboot=$2
+  exitCode=$3
   mailNotificationMode=<%= node["autopatch-nativex"]["email_notification_mode"] %>
   subject="AutoPatch ran."
   body=""
 
   #check for non-zero exit code
-  if [ $2 -gt 0 ]
+  if [ $exitCode -gt 0 ]
   then
     someErrorOccurred=true
     subject="$subject Errors: Yes"
-    body="AN ERROR OCCURRED. See full attached log for details.\n"
+    body=$'AN ERROR OCCURRED. See full attached log for details.\n'
   else
     someErrorOccurred=false
     subject="$subject Errors: No"
-    body="yum update was successful.\n"
+    body=$'Update process was successful.\n'
   fi
 
-  manualReboot=$1
-  if [ "$manualReboot" == "true" ]
+  if [[ "$manualReboot" == "true" && "$updateAttempted" == "true" ]]
   then
     subject="$subject Reboot: Yes"
-    body="Manual reboot may be required.\n"
+    body=$body$'Manual reboot may be required.\n'
   else
     subject="$subject Reboot: No"
-    body="Machine will automatically reboot.\n"
+    if [ "$updateAttempted" == "true" ]
+    then
+      body=$body$'Machine will automatically reboot.\n'
+    else
+      body=$body$'No new updates.\n'
+    fi
   fi
 
   if [[ "$mailNotificationMode" == "Always" || ( "$mailNotificationMode" == "OnlyOnErrorOrManualReboot" && ( "$someErrorOccurred" == "true" || "$manualReboot" == "true" ) ) ]]
@@ -65,27 +72,38 @@ function sendMailIfNecessary {
 }
 
 # Real work starts here
-<% if node["auto-patch"]["splay"] > 0 -%>
-sleepSeconds = $[ ( $RANDOM % <%= node["auto-patch"]["splay"] %> )  + 1 ]
-writeHostAndLogFile "Download and Install Splay is enabled. Sleeping for $sleepSeconds seconds."
-sleep $sleepSecondss
-<% else -%>
-writeHostAndLogFile "Download and Install Splay is disabled."
-<% end -%>
+writeHostAndLogFile "Checking for available updates."
+/usr/bin/yum check-update >><%= node["autopatch-nativex"]["working_dir"] %>/autopatch.log 2>&1
+checkUpdateExitCode=$?
+if [ $checkUpdateExitCode -eq 100 ]
+then
+  <% if node["auto-patch"]["splay"] > 0 -%>
+  writeHostAndLogFile "There is at least one update available. Commencing update process."
+  theSleepSeconds=$[( ( $RANDOM % <%= node["auto-patch"]["splay"] %> ) + 1 )]
+  writeHostAndLogFile "Download and Install Splay is enabled. Sleeping for $theSleepSeconds seconds."
+  sleep "$theSleepSeconds"s
+  <% else -%>
+  writeHostAndLogFile "Download and Install Splay is disabled."
+  <% end -%>
+  
+  writeHostAndLogFile "Beginning yum upgrade now!"
+  
+  /usr/bin/yum -y update >> <%= node["autopatch-nativex"]["working_dir"] %>/autopatch.log 2>&1
+  yumExitCode=$?
+  writeHostAndLogFile "Finished yum upgrade with exit code $yumExitCode"
+  
+  <% if node["auto-patch"]["reboot"] -%>
+  writeHostAndLogFile "Auto Reboot is enabled. Rebooting now!"
+  sendMailIfNecessary true false $yumExitCode
+  reboot
+  <% else -%>
+  writeHostAndLogFile "Auto Reboot is disabled. Manual reboot may be required."
+  sendMailIfNecessary true true $yumExitCode
+  <% end -%>
 
-writeHostAndLogFile "Beginning yum upgrade now!"
-
-/usr/bin/yum -y -e 0 -d 0 update >> <%= node["autopatch-nativex"]["working_dir"] %>/autopatch.log 2>>&1
-
-writeHostAndLogFile "Finished yum upgrade with exit code $?"
-
-<% if node["auto-patch"]["reboot"] -%>
-writeHostAndLogFile "Auto Reboot is enabled. Rebooting now!"
-sendMailIfNecessary false $?
-reboot
-<% else -%>
-writeHostAndLogFile "Auto Reboot is disabled. Manual reboot may be required."
-sendMailIfNecessary true $?
-<% end -%>
+else
+  writeHostAndLogFile "yum check-update returned with non-100 exit code '$checkUpdateExitCode'. Skipping update process."
+  sendMailIfNecessary false false $checkUpdateExitCode
+fi
 
 exit 0
